import { assetPath } from './assetPath.js';

export const ENEMY_SPRITES = {
  monster: {
    key: 'enemy-monster-walk',
    path: assetPath('assets/enemies/monster/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  firecaster: {
    key: 'enemy-firecaster-walk',
    path: assetPath('assets/enemies/firecaster/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  tank: {
    key: 'enemy-tank-walk',
    path: assetPath('assets/enemies/tank/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  splitter: {
    key: 'enemy-splitter-walk',
    path: assetPath('assets/enemies/splitter/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  bomber: {
    key: 'enemy-bomber-walk',
    path: assetPath('assets/enemies/bomber/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  healer: {
    key: 'enemy-healer-walk',
    path: assetPath('assets/enemies/healer/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  summoner: {
    key: 'enemy-summoner-walk',
    path: assetPath('assets/enemies/summoner/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  shielded: {
    key: 'enemy-shielded-walk',
    path: assetPath('assets/enemies/shielded/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  teleporter: {
    key: 'enemy-teleporter-walk',
    path: assetPath('assets/enemies/teleporter/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  sniper: {
    key: 'enemy-sniper-walk',
    path: assetPath('assets/enemies/sniper/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  egg: {
    key: 'enemy-egg-walk',
    path: assetPath('assets/enemies/egg/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
  slime: {
    key: 'enemy-slime-walk',
    path: assetPath('assets/enemies/slime/walk.png'),
    frameWidth: 64,
    frameHeight: 64,
  },
};

export const ENEMY_BESTIARY = [
  {
    id: 'swarmer',
    name: 'Swarmer',
    sprite: 'monster',
    frame: 0,
    tint: null,
    firstWave: 'Wave 1',
    movement: 'Moves directly toward the player from the arena edges.',
    power: 'No special attack. It wins by surrounding you and forcing movement mistakes.',
    counter: 'Keep moving, shoot while backing up, and clear groups before they close in.',
  },
  {
    id: 'tank',
    name: 'Tank',
    sprite: 'tank',
    frame: 0,
    tint: null,
    firstWave: 'Wave 10',
    movement: 'Moves slowly and directly toward the player.',
    power: 'High health. It absorbs shots while smaller enemies pressure you.',
    counter: 'Kite it around the arena and clear weaker enemies before focusing it down.',
  },
  {
    id: 'firecaster',
    name: 'Firecaster',
    sprite: 'firecaster',
    frame: 2,
    tint: null,
    firstWave: 'Wave 15',
    movement: 'Keeps distance, backs away when too close, and strafes while aiming.',
    power: 'Charges briefly, then shoots a fireball at your position.',
    counter: 'Watch for the orange flash, then dodge sideways before the shot releases.',
  },
  {
    id: 'splitter',
    name: 'Splitter',
    sprite: 'splitter',
    frame: 1,
    tint: null,
    firstWave: 'Wave 20',
    movement: 'Chases at medium speed.',
    power: 'Splits into three small fast enemies when killed.',
    counter: 'Create space before finishing it so the smaller enemies do not surround you.',
  },
  {
    id: 'bomber',
    name: 'Bomber',
    sprite: 'bomber',
    frame: 2,
    tint: null,
    firstWave: 'Wave 25',
    movement: 'Runs aggressively toward the player.',
    power: 'Flashes and explodes when close or when killed.',
    counter: 'Shoot it early and move away when it starts flashing.',
  },
  {
    id: 'egg',
    name: 'Spawner Egg',
    sprite: 'egg',
    frame: 0,
    tint: null,
    firstWave: 'Wave 35',
    movement: 'Stationary.',
    power: 'Periodically hatches small enemies until destroyed.',
    counter: 'Destroy it early so it cannot multiply the wave.',
  },
  {
    id: 'slime',
    name: 'Poison Slime',
    sprite: 'slime',
    frame: 1,
    tint: null,
    firstWave: 'Wave 40',
    movement: 'Slowly follows the player.',
    power: 'Leaves damaging poison puddles on the ground.',
    counter: 'Avoid its trail and fight it in open space.',
  },
  {
    id: 'healer',
    name: 'Healer',
    sprite: 'healer',
    frame: 0,
    tint: null,
    firstWave: 'Wave 45',
    movement: 'Stays behind the pack and avoids getting too close.',
    power: 'Periodically heals nearby enemies.',
    counter: 'Prioritize it before fighting tanks or shielded enemies.',
  },
  {
    id: 'summoner',
    name: 'Summoner',
    sprite: 'summoner',
    frame: 3,
    tint: null,
    firstWave: 'Wave 50',
    movement: 'Keeps distance and drifts away when pressured.',
    power: 'Summons weak minions over time.',
    counter: 'Push through the crowd and eliminate it before the wave grows.',
  },
  {
    id: 'dasher',
    name: 'Dasher',
    sprite: 'monster',
    frame: 1,
    tint: 0x2e7d32,
    firstWave: 'Wave 55',
    movement: 'Walks slowly, stops for a short windup, then launches into a fast dash.',
    power: 'The dash covers distance quickly after a flashing warning.',
    counter: 'When it flashes, sidestep instead of running straight away.',
  },
  {
    id: 'shielded',
    name: 'Shielded',
    sprite: 'shielded',
    frame: 0,
    tint: null,
    firstWave: 'Wave 65',
    movement: 'Faces and advances toward the player.',
    power: 'Takes reduced damage from the front.',
    counter: 'Circle around it, use spread fire, or hit it with explosions.',
  },
  {
    id: 'teleporter',
    name: 'Teleporter',
    sprite: 'teleporter',
    frame: 1,
    tint: null,
    firstWave: 'Wave 70',
    movement: 'Moves normally, then blinks near the player after a warning.',
    power: 'Teleport pressure can cut off your escape path.',
    counter: 'When it flashes purple, change direction and prepare to dash.',
  },
  {
    id: 'sniper',
    name: 'Sniper',
    sprite: 'sniper',
    frame: 2,
    tint: null,
    firstWave: 'Wave 75',
    movement: 'Maintains long range and stops to aim.',
    power: 'Draws a warning line, then fires a fast shot.',
    counter: 'Watch the line and dodge sideways before the shot releases.',
  },
  {
    id: 'boss',
    name: 'The Warden',
    sprite: 'tank',
    frame: 0,
    tint: 0x9575cd,
    firstWave: 'Every 10 waves',
    movement:
      'A huge shielded guardian that hovers near the top and tracks you, summoning minions.',
    power:
      'Energy shield blocks body hits and regenerates each phase; small orbiting weak points always damage it. Barrages projectiles, charges and ground-slams, and enrages across three phases.',
    counter:
      'Snipe the moving weak points to skip the shield, or break the shield then unload. Dodge the charge windup and stay out of slam range.',
  },
];
