name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
      checks: write # Required for dorny/test-reporter
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Security Scan
        run: npm audit --audit-level=high
      - name: Lint and Format
        run: npm run check
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test:run
      - name: Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Unit Tests
          path: junit.xml
          reporter: jest-junit
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
